models/Teams.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Teams extends ActiveRecord
{
	public $teamsCount;
	
    public static function tableName()
    {
        return 'teams';
    }

    public function getLeague(){
    	return $this->hasOne(Leagues::className(), ['id' => 'league_id']);
    }

    public function getGallery(){
    	return $this->hasMany(TeamGalleries::className(), ['team_id' => 'id']);
    }
}

controllers/HelloCrudController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\helpers\Url;
use yii\web\UploadedFile;

use app\models\Teams;
use app\models\Leagues;
use app\models\TeamsForm;
use app\models\TeamGalleries;
use app\models\TeamGalleriesForm;

class HelloCrudController extends Controller
{
   
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'detail', 'add', 'edit', 'delete', 'delete-all', 'gallery', 'add-photo', 'edit-photo', 'delete-photo'],
                'rules' => [
                    [
                        'actions' => ['index', 'detail', 'add', 'edit', 'delete', 'delete-all', 'gallery', 'add-photo', 'edit-photo', 'delete-photo'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $query = Teams::find();
        $teams = $query->orderBy('id')
            ->all();

        return $this->render('index', ['teams'=>$teams]);
    }

    public function actionDetail($id)
    {
        $team = Teams::findOne(['id'=>$id]);
        return $this->render('detail', ['team'=>$team]);
    }

    public function actionAdd()
    {
        $forms = new TeamsForm();
        
        if ($forms->load(Yii::$app->request->post()) && $forms->validate())
        {
            $request = Yii::$app->request;
            
            $team = new Teams();
            $team->name = $request->post('TeamsForm')['name'];
            $team->description = $request->post('TeamsForm')['description'];
            $team->country = $request->post('TeamsForm')['country'];
            $team->league_id = $request->post('TeamsForm')['league_id'];
            $team->save();

            return $this->redirect(Url::to(['hello-crud/index']));
        }
        else 
        {
            $leagues = Leagues::find()->select(['name', 'id'])
                                        ->indexBy('id')
                                        ->column();

                return $this->render('add', ['forms'=>$forms, 'leagues'=>$leagues]);
            
        }
    }

    public function actionEdit($id)
    {
        $forms = new TeamsForm();
        
        if ($forms->load(Yii::$app->request->post()) && $forms->validate())
        {
            $request = Yii::$app->request;
            
            $team = Teams::findOne(['id', $id]);
            $team->name = $request->post('TeamsForm')['name'];
            $team->description = $request->post('TeamsForm')['description'];
            $team->country = $request->post('TeamsForm')['country'];
            $team->league_id = $request->post('TeamsForm')['league_id'];
            $team->save();

            return $this->redirect(Url::to(['hello-crud/detail', 'id'=>$id]));
        }
        else 
        {
            $team = Teams::findOne(['id', $id]);
            $leagues = Leagues::find()->select(['name', 'id'])
                                        ->indexBy('id')
                                        ->column();

            return $this->render('edit', ['forms'=>$forms, 'leagues'=>$leagues, 'team'=>$team]);
            
        }
    }

    public function actionDelete($id)
    {
        $team = Teams::findOne(['id' => $id]);
        $team->delete();

        return $this->redirect(Url::to(['hello-crud/index']));
    }

    public function actionDeleteAll()
    {
        Teams::deleteAll();
        return $this->redirect(Url::to(['hello-crud/index']));
    }

    public function actionGallery($id)
    {
        $team = Teams::findOne(['id' => $id]);
        $galleries = TeamGalleries::find()->where(['team_id' => $id])->orderBy('id')->all();
        return $this->render('gallery', ['team'=>$team, 'galleries'=>$galleries]);
    }

    public function actionAddPhoto($id)
    {
        $forms = new TeamGalleriesForm();

        if ($forms->load(Yii::$app->request->post()) && $forms->validate())
        {
            $request = Yii::$app->request;
            $forms->photo = UploadedFile::getInstance($forms, 'photo');
            
            $team = new TeamGalleries();
            $team->name = $request->post('TeamGalleriesForm')['name'];
            $team->description = $request->post('TeamGalleriesForm')['description'];
            $team->team_id = $id;
            $team->save();
            
            $filepath = 'upload/'.$forms->photo->baseName.'_'.sha1($team->id).'.'.$forms->photo->extension;
            $forms->photo->saveAs($filepath);
            $team->filepath = $filepath;
            $team->save();
            
            return $this->redirect(Url::to(['hello-crud/gallery', 'id'=>$id]));
        }
        else 
        {
            $team = Teams::findOne(['id' => $id]);
            return $this->render('add_photo', ['team'=>$team, 'forms'=>$forms]);
        }
    }

    public function actionEditPhoto($id, $gal_id)
    {
        
        $forms = new TeamGalleriesForm();

        if ($forms->load(Yii::$app->request->post()) && $forms->validate())
        {
            $request = Yii::$app->request;
                
            $photo = TeamGalleries::findOne(['id'=>$gal_id]);
            $photo->name = $request->post('TeamGalleriesForm')['name'];
            $photo->description = $request->post('TeamGalleriesForm')['description'];
            $photo->save();
            
            return $this->redirect(Url::to(['hello-crud/gallery', 'id'=>$id]));
        }
        else 
        {
            $team = Teams::findOne(['id' => $id]);
            $photo = TeamGalleries::findOne(['id'=>$gal_id]);
            return $this->render('edit_photo', ['team'=>$team, 'forms'=>$forms, 'photo'=>$photo]);
        }
    }

    public function actionDeletePhoto($id, $gal_id)
    {
        $photo = TeamGalleries::findOne(['id'=>$gal_id]);
        unlink($photo->filepath);
        $photo->delete();

        return $this->redirect(Url::to(['hello-crud/gallery', 'id'=>$id]));        
    }

    public function generateFile($type="csv")
    {
        /* WORK IN PROGRESS */
        
    }
}

views/hello-crud/add.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Hello CRUD";

?>

<div class="row">
	<div class="col-md-12">
		<h1>Add Team</h1>
		<hr/>
		<?php

		echo Breadcrumbs::widget([
		    'itemTemplate' => "<li>{link}</li>\n", // template for all links
		    'links' => [
		    	['label' => 'Team List', 'url' => ['hello-crud/index']],
		        'Add Team',
		    ],
		]);

		?>
	</div>
</div>

<div>	
	<div class="col-md-12">
		<?php $form = ActiveForm::begin([
				'id' => 'teams-form',
				'options' => ['class' => 'form-horizontal']
			])
		?>

		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'name')->hint('Diisi dengan nama yang terdiri dari angka, huruf kecil atau huruf besar'); ?>
			</div>
		</div>
		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'country')->hint('Diisi dengan karakter hanya huruf kecil atau huruf besar'); ?>
			</div>
		</div>
		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'league_id')->dropDownList($leagues, ['prompt' => 'Mohon pilih liga'])->label('Liga') ?>
			</div>
		</div>
		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'description')->TextArea(); ?>
			</div>
		</div>
		<div class="form-group">
		    <div class="col-lg-8">
		        <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary']) ?>
		    </div>
		</div>

		<?php ActiveForm::end(); ?>
	</div>
</div>

views/hello-crud/add_photo.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Hello CRUD";

?>

<div class="row">
	<div class="col-md-12">
		<h1><?php echo $team['name'] ?> Gallery</h1>
		<hr/>

		<?php

		echo Breadcrumbs::widget([
		    'itemTemplate' => "<li>{link}</li>\n", // template for all links
		    'links' => [
		        ['label' => 'Team List', 'url' => ['hello-crud/index']],
		        ['label' => $team['name'], 'url' => ['hello-crud/detail', 'id'=>$team['id']]],
		        ['label' => 'Gallery', 'url' => ['hello-crud/gallery', 'id'=>$team['id']] ],
		        'Add New',
		    ],
		]);

		?>
	</div>
</div>

<div>	
	<div class="col-md-12">
		<?php $form = ActiveForm::begin([
				'id' => 'teams-form',
				'options' => ['class' => 'form-horizontal', 'enctype' => 'multipart/form-data']
			])
		?>

		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'photo')->fileInput(); ?>
			</div>
		</div>

		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'name')->hint('Diisi dengan nama yang terdiri dari angka, huruf kecil atau huruf besar'); ?>
			</div>
		</div>
		
		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'description')->TextArea(); ?>
			</div>
		</div>

		<div class="form-group">
		    <div class="col-lg-8">
		        <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary']) ?>
		    </div>
		</div>

		<?php ActiveForm::end(); ?>
	</div>
</div>

views/hello-crud/detail.php
<?php

use yii\widgets\Breadcrumbs;
use yii\helpers\Url;
use yii\bootstrap\Carousel;

$this->title = "Hello CRUD";

?>


<div class="row">
	<div class="col-md-12">
		<h1><?php echo $team['name'] ?></h1>
		<hr/>

		<?php

		echo Breadcrumbs::widget([
		    'itemTemplate' => "<li>{link}</li>\n", // template for all links
		    'links' => [
		        ['label' => 'Team List', 'url' => ['hello-crud/index']],
		        $team['name'],
		    ],
		]);

		?>
	</div>
</div>

<div>	
	<div class="col-md-2">
		<div class="list-group">
		  <a href="<?php echo Url::to(['hello-crud/gallery', 'id'=>$team['id']]); ?>" class="list-group-item"><i class="glyphicon glyphicon-eye-open"></i> View Gallery</a>
		  <a href="<?php echo Url::to(['hello-crud/edit', 'id'=>$team['id']]); ?>" class="list-group-item"><i class="glyphicon glyphicon-pencil"></i> Edit Team</a>
		  <a href="<?php echo Url::to(['hello-crud/delete', 'id'=>$team['id']]); ?>" class="list-group-item"><i class="glyphicon glyphicon-trash"></i> Delete Team</a>
		</div>
	</div>
	<div class="col-md-10">
		<div class="col-md-4">
			<?php

			$items = [];
			
			foreach ($team->gallery as $item){
				$items[] = [
			            'content' => '<img style="width:300px;" src="'.$item->filepath.'"/>',
			            'caption' => '<h4>'.$item->name.'</h4><p>'.$item->description.'</p>',
			        ];
			}

			echo Carousel::widget([
			    'items' => $items,
			]);

			?>
		</div>

		<div class="col-md-8">
			<p><b>League</b>: <?php echo $team->league['name'] ?></p>
			<p><b>Country</b>: <?php echo $team->country ?></p>
			<p><?php echo $team['description'] ?></p>

		</div>		
</div>

views/hello-crud/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Hello CRUD";

?>

<div class="row">
	<div class="col-md-12">
		<h1>Edit <?php echo $team['name'] ?></h1>
		<hr/>
		<?php

		echo Breadcrumbs::widget([
		    'itemTemplate' => "<li>{link}</li>\n", // template for all links
		    'links' => [
		    	['label' => 'Team List', 'url' => ['hello-crud/index']],
		        'Edit '.$team['name'],
		    ],
		]);

		?>
	</div>
</div>

<div>	
	<div class="col-md-12">
		<?php $form = ActiveForm::begin([
				'id' => 'teams-form',
				'options' => ['class' => 'form-horizontal']
			])
		?>

		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'name')->textInput(['value'=>$team->name])->hint('Diisi dengan nama yang terdiri dari angka, huruf kecil atau huruf besar'); ?>
			</div>
		</div>
		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'country')->textInput(['value'=>$team->country])->hint('Diisi dengan karakter hanya huruf kecil atau huruf besar'); ?>
			</div>
		</div>
		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'league_id')->dropDownList($leagues, ['options' => [$team->league_id => ['Selected'=>true]]], ['prompt' => 'Mohon pilih liga'])->label('Liga') ?>
			</div>
		</div>
		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'description')->TextArea(['value'=>$team->description]); ?>
			</div>
		</div>
		<div class="form-group">
		    <div class="col-lg-8">
		        <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary']) ?>
		    </div>
		</div>

		<?php ActiveForm::end(); ?>
	</div>
</div>

views/hello-crud/edit_photo.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Hello CRUD";

?>

<div class="row">
	<div class="col-md-12">
		<h1>Edit Photo</h1>
		<hr/>

		<?php

		echo Breadcrumbs::widget([
		    'itemTemplate' => "<li>{link}</li>\n", // template for all links
		    'links' => [
		        ['label' => 'Team List', 'url' => ['hello-crud/index']],
		        ['label' => $team['name'], 'url' => ['hello-crud/detail', 'id'=>$team['id']]],
		        ['label' => 'Gallery', 'url' => ['hello-crud/gallery', 'id'=>$team['id']] ],
		        'Edit ',
		    ],
		]);

		?>
	</div>
</div>

<div>	
	<div class="col-md-12">
		<?php $form = ActiveForm::begin([
				'id' => 'teams-form',
				'options' => ['class' => 'form-horizontal', 'enctype' => 'multipart/form-data']
			])
		?>

		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'name')->textInput(['value'=>$photo['name']])->hint('Diisi dengan nama yang terdiri dari angka, huruf kecil atau huruf besar'); ?>
			</div>
		</div>
		
		<div class="form-group">
		    <div class="col-lg-8">
			<?= $form->field($forms, 'description')->TextArea(['value'=>$photo['description']]); ?>
			</div>
		</div>

		<div class="form-group">
		    <div class="col-lg-8">
		        <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary']) ?>
		    </div>
		</div>

		<?php ActiveForm::end(); ?>
	</div>
</div>

views/hello-crud/gallery.php
<?php

use yii\widgets\Breadcrumbs;
use yii\helpers\Url;
use yii\helpers\Html;

$this->title = "Hello CRUD";

?>


<div class="row">
	<div class="col-md-12">
		<h1><?php echo $team['name'] ?> Gallery</h1>
		<hr/>

		<?php

		echo Breadcrumbs::widget([
		    'itemTemplate' => "<li>{link}</li>\n", // template for all links
		    'links' => [
		        ['label' => 'Team List', 'url' => ['hello-crud/index']],
		        ['label' => $team['name'], 'url' => ['hello-crud/detail', 'id'=>$team['id']]],
		        'Gallery',
		    ],
		]);

		?>
	</div>
</div>

<div>	
	<div class="col-md-2">
		<div class="list-group">
		  <a href="<?php echo Url::to(['hello-crud/add-photo', 'id'=>$team['id']]); ?>" class="list-group-item"><i class="glyphicon glyphicon-eye-open"></i> Add New</a>
		</div>
	</div>
	<div class="col-md-10">
		<table class="table table-striped">
		    <thead>
		      <tr>
		        <th>Name</th>
		        <th>Description</th>
		        <th>File Path</th>
		        <th>Action</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<?php if (count($galleries) > 0) { ?>
					<?php foreach ($galleries as $item): ?>
					    <tr>
					        <td><?= Html::encode("{$item['name']}") ?></td>
					        <td><?= Html::encode("{$item['description']}") ?></td>
					        <td><?= Html::encode("{$item['filepath']}") ?></td>
					        <td style="width:15%;text-align:center;">
					        	<a class="btn btn-success btn-sm" href="<?php echo Url::to(['hello-crud/edit-photo', 'id'=>$team['id'], 'gal_id'=>$item['id']]); ?>"><i class="glyphicon glyphicon-pencil"></i></a> 
					        	<a class="btn btn-danger btn-sm" href="<?php echo Url::to(['hello-crud/delete-photo', 'id'=>$team['id'], 'gal_id'=>$item['id']]); ?>"><i class="glyphicon glyphicon-trash"></i></a> 
					        </td>
					      </tr>
					<?php endforeach; ?>
				<?php } else { ?>
			    <tr>
			    	<td style="text-align:center;font-size:15px;padding:25px;" colspan="5">No data found...</td>
			    </tr>
			    <?php } ?>
		      
		    </tbody>
		</table>
	</div>
</div>

views/hello-crud/index.php
<?php

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = "Hello CRUD";

?>

<div class="row">
	<div class="col-md-12">
		<h1>Team List</h1>
		<hr/>
		<?php

		echo Breadcrumbs::widget([
		    'itemTemplate' => "<li>{link}</li>\n", // template for all links
		    'links' => [
		        'Team List',
		    ],
		]);

		?>
	</div>
</div>

<div>	
	<div class="col-md-2">
		<div class="list-group">
		  <a href="<?php echo Url::to(['hello-crud/add']); ?>" class="list-group-item"><i class="glyphicon glyphicon-plus"></i> Add Team</a>
		  <a href="<?php echo Url::to(['hello-crud/delete-all']); ?>" class="list-group-item"><i class="glyphicon glyphicon-trash"></i> Delete All</a>
		</div>
	</div>
	<div class="col-md-10">
		<table class="table table-striped">
		    <thead>
		      <tr>
		        <th>Name</th>
		        <th>League</th>
		        <th>Country</th>
		        <th>Action</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<?php if (count($teams) > 0) { ?>
					<?php foreach ($teams as $team): ?>
					    <tr>
					        <td><?= Html::encode("{$team['name']}") ?></td>
					        <td><?= Html::encode("{$team->league['name']}") ?></td>
					        <td><?= Html::encode("{$team['country']}") ?></td>
					        <td style="width:15%;text-align:center;">
					        	<a class="btn btn-success btn-sm" href="<?php echo Url::to(['hello-crud/detail', 'id'=>$team['id']]); ?>"><i class="glyphicon glyphicon-eye-open"></i></a> 
					        </td>
					      </tr>
					<?php endforeach; ?>
				<?php } else { ?>
			    <tr>
			    	<td style="text-align:center;font-size:15px;padding:25px;" colspan="5">No data found...</td>
			    </tr>
			    <?php } ?>
		      
		    </tbody>
		  </table>
	</div>
</div>